usagov/vote-gov

config.toml
gulpfile.js
package.json

This PR lays the foundation of the site. Based on @maya's internationalization research and experience on the team with this stack, we're using Hugo, a static site generator, with npm and gulp for dependency management and build creation respectively.

Creates Hugo, npm and gulp scaffolding

---

README.md
package.json

These installation instructions will quickly get a user up and running with the project. I would like to flesh them out a little with your help @kategarklavs. Thanks!

Update installation / development documentation

---

assets/styles/main.scss
layouts/index.html
layouts/partials/disclaimer.html
layouts/partials/footer.html
layouts/partials/go-back.html
layouts/partials/header.html
layouts/partials/navbar.html
layouts/states/register-by-mail.html
layouts/states/register-in-person.html
layouts/states/register-not-needed.html
layouts/states/register-online.html
layouts/states/single.html
npm-debug.log

This adds in the latest design updates, cc @ericadeahl.
Resolves #11.

Add design updates

---

.scss-lint.yml
assets/scripts/start.js
assets/styles/main.scss

This patch series fixes all the current linting errors in the repository referenced in #51 🎉
This PR needs to be merged into `continuous-deployments` in order to finish up the work on deployments. This should clear up the failures currently on that branch.

Fix all linting errors

---

README.md

This patch series adds `staging` and `master` badges from CircleCI to the `README`.

Add CircleCI badges for build visibility

---

README.md

Just updated one instance of passive voice.

Changed passive > active voice

---

README.md

Just reviewed this and made a few tiny copy edits — IMO, it's ready to go!

Minor copy edits

---

assets/styles/component/disclaimer.scss
assets/styles/main.scss
data/translations/english/states.toml
data/translations/spanish/states.toml
layouts/partials/disclaimer.html
layouts/partials/header.html
layouts/partials/language-switcher.html

This PR can be previewed here 👀 => https://vote-gov-language-switcher.apps.cloud.gov/
Closes #26 
cc: @ericadeahl

Add language switcher

---

content/register/rhode-island.md

Update Rhode Island to online registration

---

config/gulp/build.js
config/gulp/lang/spanish/state-names.json

Reflects the TOML Spanish state name changes into the JSON file used for creating the content files. Also includes an improvement to the build script, to let us see Hugo errors.

States json fixes

---

layouts/partials/header.html

Fix logo link to correct language homepage

---

data/translations/english/meta.toml
data/translations/spanish/meta.toml
layouts/partials/head.html

We want the open graph metadata to be translated. This PR should achieve that.

tweaking how open graph metadata works

---

assets/scripts/start.js
layouts/index.html
layouts/partials/scripts.html
package.json

... because we don't actually need it, and _Every Line Of Code Is A Liability&trade;_.

Remove all front-end JS other than analytics

---

content/register/ca.md
content/register/gu.md
content/register/la.md
content/register/mo.md
content/register/wy.md

Some states/territories still don't support it, those have been left unmodified.

Use HTTPS links to voter registration

---

README.md

The links were not displaying properly.

fixed link formatting in readme

---

config.toml

This returns access to the list of states in the dropdown.

Restore dropdown

---

content/en/register/md.md

Maryland changed the link for their online registration tool

Update Maryland online registration link

---

content/en/register/oh.md
content/es/registrar/oh.md

Updates the Ohio online voter registration URL in:
Resolves https://github.com/usagov/vote-gov/issues/246
I haven't checked whether this builds or not.

Update Ohio online voter registration URL

---

layouts/partials/footer.html

add eac logo

---

config/gulp/lang/spanish/state-names.json
content/en/register/ri.md
content/es/registrar/ri.md

Changed link URL to the Spanish RI site

Update RI URL

---

config/gulp/lang/spanish/state-names.json
content/en/register/al.md
content/en/register/as.md
content/en/register/az.md
content/en/register/co.md
content/en/register/de.md
content/en/register/fl.md
content/en/register/nv.md
content/en/register/ny.md
content/en/register/pa.md
content/en/register/wa.md
content/en/register/wv.md
content/es/registrar/al.md
content/es/registrar/as.md
content/es/registrar/az.md
content/es/registrar/de.md
content/es/registrar/fl.md
content/es/registrar/nv.md
content/es/registrar/ny.md
content/es/registrar/pa.md
content/es/registrar/wa.md
content/es/registrar/wi.md
content/es/registrar/wv.md

Alabama Spanish page - now redirects to an English registration page.

Updating redirected link

---

data/registration_forms/bengali.toml
data/registration_forms/chinese.toml
data/registration_forms/english.toml
data/registration_forms/hindi.toml
data/registration_forms/japanese.toml
data/registration_forms/khmer.toml
data/registration_forms/korean.toml
data/registration_forms/spanish.toml
data/registration_forms/tagalog.toml
data/registration_forms/vietnamese.toml

Update link to Bengali PDF

---

layouts/partials/header.html

I have no idea if this will work.

Inserted a "/" so the state pages will get to the home page

---

data/translations/english/register.toml

Updated text for in person registration

Updated text for in person registration

---

data/translations/spanish/register.toml

updated Spanish registration text online, in person and not needed

Updated Spanish registration text

---

config/gulp/lang/spanish/state-names.json
content/en/register/as.md
content/es/registrar/as.md

Updated URL to https://aselectionoffice.gov/

Updated URL for American Samoa

---

config/gulp/lang/spanish/state-names.json
content/en/register/al.md
content/en/register/ct.md
content/en/register/wi.md
content/es/registrar/al.md
content/es/registrar/ct.md
content/es/registrar/wi.md

Redirects for states - both English and Spanish

---

data/translations/english/register.toml
data/translations/spanish/register.toml

Update registration text for no registration needed (example: North Dakota)

Update registration text

---

config/gulp/lang/spanish/state-names.json
content/es/registrar/ca.md

change URL to go directly to Spanish page

update CA URL

---

content/en/register/co.md
content/en/register/gu.md
content/en/register/mo.md
content/en/register/nh.md
content/en/register/nm.md
content/en/register/ri.md
content/en/register/ut.md
content/en/register/wy.md

Updated link to https://gec.guam.gov/index.php/for-voters/for-voters

Update Guam link

---

data/translations/english/register.toml
data/translations/spanish/register.toml

Updated the text to include National Voter Registration form

Updated the text for Mail in registration

---

content/en/register/nc.md
content/es/registrar/nc.md

North Carolina was a mail in registration state, but now offers online voter registration: https://www.ncdot.gov/dmv/offices-services/online/Pages/voter-registration-application.aspx

Updated North Carolina to online registration

---

data/translations/spanish/register.toml

Sg state update

---

config/gulp/state-data.json

Updated links for Delaware, Florida, Nebraska, Northern Mariana Islands, Rhode Island and Texas

Updated links

---

data/translations/english/register.toml
data/translations/spanish/register.toml
layouts/partials/by-mail.html
layouts/partials/in-person.html
layouts/partials/not-needed.html
layouts/partials/online.html

Sinchagrenchik online update

---

config/gulp/state-data.json

DC no longer has online registration - changed the page to mail in.

Changed DC page from Online to Mail In

---

data/translations/english/register.toml

Added the word "General" to h2 heading "General election day in state_name"

Added "General" to election day

---

config/gulp/state-data.json

Fix broken links

---

config/gulp/state-data.json

Needed to add English Only to Guam links on Spanish Page

Added English Only to Guam Spanish Page

---

config/gulp/state-data.json

online voting in Florida has to go through Eng to get to Spa

Changed URL

---

config/gulp/state-data.json

Updated other way to vote URL in Eng and Spa per Michigan's request via USA.gov email

Changed Link

---

config/gulp/state-data.json

Updated the registration deadlines for Arkansas, Louisiana, South Carolina, Tennessee

Updated dates for AR, LA, SC, TN

---

config/gulp/state-data.json

Changing mail in deadline for Florida from received by to postmarked by.

Change FL Mail in from Recieved by to post marked

---

config/gulp/state-data.json

Arizona changed it's registration deadline from Oct. 5 to Oct. 23. Mail in registration is also now "received by"

Change registration deadline for AZ

---

config/gulp/state-data.json
data/translations/english/register.toml
data/translations/spanish/register.toml
layouts/partials/deadlines.html

The "check your voter registration" links for all the states have been added

Confirm registration links added to staging

---

config/gulp/state-data.json

Updated registration deadline in Arizona from Oct 23 to Oct 15

Updated deadline in AZ

---

config/gulp/state-data.json
content/en/register/id.md
content/es/registrar/id.md

This resolves a conflict between the staging and master branches.

Reset staging

---

config/gulp/state-data.json

States: DE, GA, ID, KY, MO, NE, NV, VT

updated text on mail received date

---

layouts/partials/header.html
layouts/partials/language-switcher.html

Added translation to "Skip to main content"

Skip sp sg

---

layouts/index.html
layouts/partials/analytics.html
layouts/partials/scripts.html

Removed some analytics scripts from vote.gov's DOM

move Analytic Scripts

---

config/gulp/state-data.json

Changed Iowa from 11 days to 15 days - also changed received by to postmarked by

Updated Iowa

---

package-lock.json

This update is just maintenance on the existing packages. We should always periodically check for available updates that can reduce vulnerabilities and improve code security.

Update node modules to latest stable versions

---

assets/styles/main.scss
cypress.json
cypress/integration/accessibility/axe.spec.js
cypress/plugins/index.js
cypress/support/index.js
data/translations/en/error.json
data/translations/en/register.json
data/translations/es/error.json
layouts/404.html
layouts/partials/deadlines.html
layouts/partials/footer.html
layouts/partials/links/confirm-registration-link.html
package-lock.json
package.json

CHANGELOG:
VOTE-270 Update wyoming display text for registration confirmation link
VOTE-203 updates for node packages
VOTE-277 Add Accessibility unit testing
VOTE-292 Fix mobile footer styling issue
@jpyuda

Maintenance: Adding accessibility unit test, updates to npm packages, resolving mobile layout issue

---

assets/styles/main.scss
data/translations/es/error.json
layouts/404.html
layouts/partials/footer1.html

moves 404 page heading and adds custom footer

VOTE-208 - Updates 404 page design

---

assets/styles/component/_language-switcher.scss
assets/styles/component/search.scss
assets/styles/main.scss
config/_default/languages.json
data/translations/bn/homepage.json
data/translations/en/homepage.json
data/translations/es/homepage.json
data/translations/hi/homepage.json
data/translations/km/homepage.json
data/translations/zh-hans/homepage.json
data/translations/zh/homepage.json
layouts/index.html
layouts/partials/header.html
layouts/partials/search.html

Implements styled search component in header for english search results

Vote 398/search

---

data/translations/es/accordion.json

Added the Spanish accordion content JSON file

VOTE-449: Adding the Spanish homepage accordion content

---

data/registration_forms.json

CHANGELOG:
Hotfix: Disable sitewide email
@jpyuda

Hotfix: disable site email

---

content/en/promoting-access-to-voting.html
data/translations/ypk/accordion.json

VOTE-583 Fix Yup'ik accordion label
@jpyuda

Hotfix for adding english modernization sheet to the sitemap and fixing Yup'ik accordion translation

---

content/es/registrar/wy.md
data/translations/es/register.json
data/translations/es/state-data.json

1. Replace "confirm registration" default link with a link to the Spanish PDF
2. Updated the paragraph and link text with Stelu's translation

VOTE-617/wyoming-link-spanish

---

content/es/registrar/sc.md
data/translations/es/state-data.json

Spanish link has a 404 error now

Hotfix to replace broken Spanish link for SC

---

cypress/e2e/externalLinks/english-external-links-validator.cy.js
cypress/e2e/externalLinks/spanish-external-links-validator.cy.js

Rhode Island and South Carolina links

Vote 678 exclude links from cypress test

---

cypress/e2e/externalLinks/english-external-links-validator.cy.js
cypress/e2e/externalLinks/spanish-external-links-validator.cy.js

Flagged 503 error does not indicate the link is actually broken

Exclude Ohio link from test

---

layouts/partials/head.html

This reverts commit 7d6e4addecc8056af367292d279ed982fe509a34.

Revert "VOTE-291 Update google tag manager"

---

config/_default/config.json

Mid-sprint Release: from STAGING to MASTER

---

cypress/e2e/externalLinks/english-external-links-validator.cy.js
cypress/e2e/externalLinks/spanish-external-links-validator.cy.js
cypress/fixtures/excluded-links-english.json
cypress/fixtures/excluded-links-spanish.json

This Pr will exclude Arizona links that were failing.
[https://bixal-projects.atlassian.net/browse/VOTE-837](url)
pull down branch
run npm run start
spilt terminal
run npm run cy:open and selected that excluded links test and ensure they are passing
also very that excluded links test are in their own folder and do not run when running the command npm run cy:proofer

updated failing links for Arizona

---

content/bn/register/ny.md
content/en/register/ny.md
content/es/registrar/ny.md
content/hi/register/ny.md
content/km/register/ny.md
content/ko/register/ny.md
content/nv/register/ny.md
content/tl/register/ny.md
content/vi/register/ny.md
content/ypk/register/ny.md
content/zh-hans/register/ny.md
content/zh/register/ny.md
data/translations/bn/state-data.json
data/translations/en/state-data.json
data/translations/es/state-data.json
data/translations/hi/state-data.json
data/translations/km/state-data.json
data/translations/ko/state-data.json
data/translations/nv/state-data.json
data/translations/tl/state-data.json
data/translations/vi/state-data.json
data/translations/ypk/state-data.json
data/translations/zh-hans/state-data.json
data/translations/zh/state-data.json

[VOTE-921](https://bixal-projects.atlassian.net/browse/VOTE-921) this updates the new york registration dates for all languages

VOTE-921: update NY reg deadline

---

content/bn/register/me.md
content/bn/register/mn.md
content/bn/register/pa.md
content/bn/register/sd.md
content/bn/register/ut.md
data/translations/bn/state-data.json

CHANGELOG:
VOTE-985: update discrepencies in bengali received deadlines
@jpyuda

HOTFIX: Release STAGING to MASTER

---

data/translations/zh-hans/register.json

[VOTE-1193](https://bixal-projects.atlassian.net/browse/VOTE-1193)
Hot fix to remove extra underscore on variable name causing NVRF heading to not show

VOTE-1193: fixes variable name

---

data/translations/zh-hans/register.json

CHANGELOG:
VOTE-1193 fix variable name for NVRF tool heading in zh-hans
@jpyuda

HOTFIX release: staging to master

---

content/bn/register/gu.md
content/bn/register/nh.md
content/en/register/gu.md
content/en/register/nh.md
content/es/registrar/gu.md
content/es/registrar/nh.md
content/hi/register/gu.md
content/hi/register/nh.md
content/km/register/gu.md
content/km/register/nh.md
content/ko/register/gu.md
content/ko/register/nh.md
content/nv/register/gu.md
content/nv/register/nh.md
content/tl/register/gu.md
content/tl/register/nh.md
content/vi/register/gu.md
content/vi/register/nh.md
content/ypk/register/gu.md
content/ypk/register/nh.md
content/zh-hans/register/gu.md
content/zh-hans/register/nh.md
content/zh/register/gu.md
content/zh/register/nh.md
data/states.json

https://bixal-projects.atlassian.net/browse/VOTE-1248
Testing steps:
Launch the site in the browser
Check the state pages for Guam and New Hampshire. Verify the text displayed coincides with the registration types.

VOTE-1248/ Update registration types for GU and NH

---

content/es/promoviendo-acceso-al-voto.html
content/tl/about-us.html
content/vi/about-us.html
content/ypk/about-us.html
content/zh-hans/about-us.html
content/zh/about-us.html

this resolves the inconsistency issues we found when migrating meta tags for [VOTE-1356](https://bixal-projects.atlassian.net/browse/VOTE-1356)

VOTE-1356: fix meta overrides key name

---

cypress/e2e/externalLinks/english-external-links-validator.cy.js
cypress/e2e/externalLinks/spanish-external-links-validator.cy.js
cypress/fixtures/excluded-links-english.json
cypress/fixtures/excluded-links-spanish.json

Pull branch
start local
run ```npx cypress run --spec "cypress/e2e/externalLinks/english-external-links-validator.cy.js"```
run ```npx cypress run --spec "cypress/e2e/externalLinks/spanish-external-links-validator.cy.js"```
Verify that all tests are passing

exclude us virgin island failing links

---

cypress/e2e/externalLinks/english-external-links-validator.cy.js
cypress/e2e/externalLinks/spanish-external-links-validator.cy.js
cypress/fixtures/excluded-links-english.json
cypress/fixtures/excluded-links-spanish.json

VOTE-1561 exclude bad responses from virgin island links
@jpyuda

Sprint 34 release addition: STAGING and MASTER

---

cypress/e2e/externalLinks/english-external-links-validator.cy.js
cypress/e2e/externalLinks/spanish-external-links-validator.cy.js
cypress/fixtures/excluded-links-english.json
cypress/fixtures/excluded-links-spanish.json

Pull branch
start local
run ```npm run cy:proofer```
Verify that New York failing tests are passing

fix NewYork failing tests

---

layouts/partials/scripts.html

[VOTE-1606](https://bixal-projects.atlassian.net/browse/VOTE-1606)

VOTE-1606 Add touchpoints for english translation

---

cypress.config.js
cypress/e2e/tests/language-switcher.cy.js
cypress/fixtures/language-switcher-pages.json
cypress/fixtures/language-translations.json

Pull branch
start local
run ```npm run cy:test```
Verify ```language-switcher.cy.js``` tests are passing

fix language switcher not to be dependent on content order

---

config/_default/languages.json

https://bixal-projects.atlassian.net/browse/VOTE-1600

VOTE-1600 Add out of synch notif to Yup'ik pages

---

config/_default/config.json
cypress/e2e/tests/footer.cy.js
data/translations/ar/footer.json
data/translations/bn/footer.json
data/translations/hi/footer.json
data/translations/ht/footer.json
data/translations/km/footer.json
data/translations/ko/footer.json
data/translations/nv/footer.json
data/translations/pt/footer.json
data/translations/ru/footer.json
data/translations/tl/footer.json
data/translations/vi/footer.json
data/translations/ypk/footer.json
data/translations/zh-hans/footer.json
data/translations/zh/footer.json
layouts/partials/contact-identifier.html

[VOTE-1619](https://bixal-projects.atlassian.net/browse/VOTE-1619)
Adds trialling slashes to fix redirects

VOTE-1619: add trailing slash

---

layouts/partials/alert-notification.html

ticket: [Vote-1684](https://bixal-projects.atlassian.net/jira/software/c/projects/VOTE/boards/254?modal=detail&selectedIssue=VOTE-1684&assignee=611272e0eb7aef00694b8a97)
Purpose: This PR will update the link on "Page being updated" alert to link back to English Homepage
to test:
1. pull down branch 
2. start local 
3. visit `http://localhost:1313/nv/register/ak/`,  `http://localhost:1313/nv/register/al/`, `http://localhost:1313/nv/register/nd/` and check that the link takes you back to  the English home page

Vote-1684 -> updated href to go to english home page

---

config/_default/languages.json
cypress/fixtures/language-translations.json

https://bixal-projects.atlassian.net/browse/VOTE-1857

VOTE-1857 update russian translation of sitename

---

assets/styles/component/language-switcher.scss
layouts/partials/language-switcher.html

[VOTE-1899](https://bixal-projects.atlassian.net/browse/VOTE-1899)
Update language switcher styling to latest design.

VOTE-1899: implement new switcher style

---

data/translations/fr/homepage.json

https://cm-jira.usa.gov/browse/VOTE-162

VOTE-162 enable French site search

---

data/translations/fr/homepage.json
data/translations/ht/homepage.json
package-lock.json

CHANGELOG:
VOTE-229 Cypress dependency updates
VOTE-162 Enable French site search
VOTE-87 Display HT site search block
@jpyuda

Sprint 40: release to MASTER

---

assets/styles/component/accordion.scss

https://cm-jira.usa.gov/browse/VOTE-235

VOTE-235 update accordion font weight

---

cypress/e2e/tests/footer.cy.js
package-lock.json
package.json

Ticket: [Vote-376](https://cm-jira.usa.gov/browse/VOTE-376)
Purpose: Updates from dependabot and to test from update 
Closes out - https://github.com/usagov/vote-gov/pull/904, https://github.com/usagov/vote-gov/pull/922
Testing: 
1. pull down branch 
2. run `npm install`
3. run `npm run cy:axe`, `npm run cy:test`, `npm run cy:open` and ensure no errors are happening

Vote-376 -> Dependabot updates - static

---

assets/styles/component/accordion.scss
assets/styles/component/sign-up.scss

https://cm-jira.usa.gov/browse/VOTE-348

VOTE-348 update line-height overrides to be minimum of 1.5

---

layouts/partials/head.html

Jira ticket: https://cm-jira.usa.gov/browse/VOTE-288
Confirm there are no duplicate meta description or titles on the homepages

Bug/vote 288/duplicate meta descriptions

---

assets/styles/component/language-switcher.scss
cypress/fixtures/site-pages.json

CHANGELOG:
VOTE-491 bugfix navajo language selector
VOTE-476 exclude Guam link from link validation test
@jpyuda

Sprint 45: release to MASTER

---

cypress/e2e/tests/state-selection.cy.js
layouts/index.html

Ticket: [Vote-536](https://cm-jira.usa.gov/browse/VOTE-536)
Purpose:  This PR will update the state selector test with the new function of the tool 
Testing:
1 - pull-down branch 
2 - run `npm run start`
3 - spilt terminal 
4 - run `npm run cy:test` and `npm run cy:open` and select the state selector test and verify that it is passing

Vote-536:  Sate Selector Test Update

---

cypress/e2e/tests/state-selection.cy.js
cypress/support/commands.js
package-lock.json
package.json

Added plugin for native event compared to the default simulated event from Cypress 
plugin - https://github.com/dmtrKovalenko/cypress-real-events

Hotfix- state selector test 

---

content/fr/sitemap.html
data/translations/fr/footer.json

[Vote-557](https://cm-jira.usa.gov/browse/VOTE-557)
This PR will add the sitemap for the French translation
n/a
n/a
1. visit [preview link]() and check that metadata is correct and the page renders correctly

Vote-557: Add French Sitemap

---

data/translations/nv/homepage.json
layouts/index.html

[Vote-558](https://cm-jira.usa.gov/browse/VOTE-558)
This Pr will update the state selector text to the approved text
n/a
n/a
1. visit [preview link](https://cg-9e8debaf-b030-4825-a43c-cb2bc850c96c.sites.pages.cloud.gov/preview/usagov/vote-gov/feature/vote-558-navajo-state-text/nv/) and ensure there are no visual issues and text as been update

Vote-558: Navajo state selector text

---

layouts/partials/links/state-primary-alert-link.html

Update the link in the primaries alert to point to eac.gov

Update primary alert link
