usagov/vote-gov

assets/styles/main.scss, layouts/index.html, layouts/states/register-by-mail.html
This adds the following design updates:
**Homepage**:
**Internal page**:
This is what it looks like:
cc: @ericadeahl @carodew @rogeruiz 
Partly addresses: https://github.com/18F/vote-gov/issues/10.
=> Add design updates

assets/scripts/start.js, config/gulp/build.js, config/gulp/flags.js, config/gulp/scripts.js, gulpfile.js, layouts/index.html, layouts/states/single.html, package.json
This patch adds the Browserify support from the `ffd-*` projects to the
repo. The entry point for the JavaScript is in `assets/scripts/start.js`
Modules can be referenced from any directory within `assets/scripts/`.
=> Add Browserify support

.editorconfig, .eslintrc, package.json
This patch series adds the base `dot-files` to the repository regarding ESLint and EditorConfig from the `ffd-toolkit`.
=> Add base files from `ffd-toolkit`

layouts/partials/header.html
There's an extra slash on the staging site when you click the logo link. This removes the slash from it.
Extra slash:
=> Remove trailing slash in logo link

circle.yml, config/ci/install-hugo.sh
This patch series adds a `install-hugo` shell script which will pull a versioned version of `hugo` from the Github releases of the `spf13/hugo` repository.
The work for this script was done by @nathany, [repo reference](https://github.com/nathany/hugo-deploy), and [discussed here in the Hugo Discourse](https://discuss.gohugo.io/t/my-deployment-process/807).
I tested this script locally to ensure that the script worked by downloading the correctly versioned file to my local directory. ~~I will test this on CircleCI using the `Build with SSH` feature and post the results.~~ The output of `hugo version` should confirm that `hugo` has been installed in the `$PATH`.
=> Add installation script for Hugo

README.md
This patch adds a link to the `wiki` for this repo.
=> Add a link to the wiki

content/register/north-dakota.md, layouts/register/types/not-needed.html
This PR:
- Adds link to external sites for "learn more"
- Updates text to say: "Learn more about voting in [your state]"
This is what it looks like:
Resolves: #65.
=> Update "learn more" link on "No registration needed" page

circle.yml, config.toml, config_en.toml, config_es.toml, package.json
When #33 landed, it broke the deployments because of a `go panic` caused with Hugo. I opened a ticket here spf13/hugo#2174 to alert the maintainers of `hugo` about the problem. I will outline in the PR what I did to fix it.
This patch series also includes some refactoring of the `npm run` scripts along with leveraging the `npm config` to establish some repeatable environmental variables. You can [find out more about that here](https://docs.npmjs.com/misc/scripts).
=> Fix deployments

content/register/tennessee.md, content/register/texas.md
tennessee.md and texas.md had swapped information. Now they have the correct information.
=> Fixing typos which swapped TX and TN.

config/gulp/build.js
@maya brought up that the watch task was still watching for the old `styles:homepage` task. This patch fixes the issue.
=> Update styles task reference

.gitignore, circle.yml, config.toml, config/gulp/build.js, config/gulp/deploy.js, config_es.toml, gulpfile.js, layouts/_default/section.html, layouts/partials/go-back.html, layouts/partials/header.html, layouts/partials/language-switcher.html, package.json
:eyes: https://vote-gov-staging-multilingual.apps.cloud.gov/
:eyes: https://vote-gov-staging-multilingual.apps.cloud.gov/es/
This patch series is rebased on top of #70 and needs #70 to be merged in before it can merged in. The work on here is the initial work of deploying the site in a multilingual environment. Currently, it is deployed manually using a local script.
Since @ericadeahl will have updated designs for the language switcher, we can tackle the last one with the design updates.
=> Multilingual deployments

layouts/register/new-pages/check-your-registration.html, layouts/register/new-pages/find-your-polling-place.html, layouts/register/new-pages/learn-about-voting-in-your-state.html, layouts/register/new-pages/no-polling-place-found.html, layouts/register/new-pages/state-voting-guide.html, layouts/register/new-pages/your-polling-place.html
Adds new page layouts. 
**TODOs**:
For reference, the following templates have unique views for each state:
- home page with state selected
- your polling place
- state voting guide
We can start with a demo state for each of these similar to how we did the registration pages, before adding all states.
These pages are singular:
- check your registration
- find your polling place
- no polling place found
- learn about voting
Then translations can be added in, but might be another PR.
cc: @rogeruiz
=> Add new pages

content/register/minnesota.md
The existing link for Minnesota voter registration redirects to an error page. This change would update the link to a valid URL.
=> Update MN voter registration website link

content/register/kansas.md
Originally proposed for usagov/vote-2016: https://github.com/usagov/vote-2016/pull/2.
Then @jwbowers told me about 18F/vote-gov: https://github.com/presidential-innovation-fellows/vote-2016/issues/116.
Cheers and thank you for helping people register to vote!
=> Update KS voter registration website link

data/translations/english/homepage.toml, data/translations/english/micro_copy.toml, data/translations/english/register.toml
States like New Jersey and Idaho do not have online registration. You can change the language again, if you think there's a saying that makes more sense, but it's important to make sure that distinction was being made between them and state with online registration.
=> Updated language

data/translations/english/states.toml, data/translations/spanish/states.toml
#110 unfortunately broke the TOML parser due to accented chars in key names. It also changed some Spanish state names but didn't update the corresponding `file` attributes in `english/states.toml`. This PR aims to fix both issues.
=> States toml fixes

layouts/index.html
We don't want the button on the homepage to be disabled, we want it to be secondary.
h/t to @maya for catching this
=> change button class

data/translations/spanish/states.toml
`[rhode island]` needs a hyphen.
=> Fix bare spaces in key name

config/gulp/deploy.js, layouts/index.html, nginx.conf
Currently, the front page form gives a 404 if the user has JS disabled, or if the button click event fails to fire. This PR adds an `nginx.conf` file, based on the standard [`static-buildpack` config](https://github.com/cloudfoundry/staticfile-buildpack/blob/master/conf/nginx.conf) with a couple of additional rewrite rules so that the form works without JS. (A couple of minor tweaks to the form were also needed to ensure that language choice is carried across.)
Currently deployed here: https://vote-gov-no-js.apps.cloud.gov/
In theory we could remove the front page JS entirely, since this config now takes care of page routing, but this PR doesn't do that.
=> Support no/broken Javascript on front page form

circle.yml
Tweaks the CircleCI config to use [Autopilot](https://github.com/contraband/autopilot), which keeps the app up during deploys.
=> Zero downtime push

layouts/index.html, nginx.conf
Following @jamesharnett's [comment](https://github.com/18F/vote-gov/issues/124#issuecomment-249396839), this tweak ensures that users who click the big _Find out how to register_ button without choosing a state are just returned to the front page.
Additional possible tweaks:
* A JS tweak suggested by @jamesharnett - disable the submit button until the stat is selected.
* A non-JS tweak: Redirect to a second index page which includes an extra note reminding the user that they have to choose a state.
=> Tweak to catch clicks without selection

layouts/partials/analytics.html, layouts/partials/scripts.html
Switches back from using the 18F/labs.usa.gov ID to the PIF/vote.usa.gov ID.
=> Update analytics IDs for DAP

layouts/register/types/by-mail.html
URLs were relative. We need them to be absolute. This should fix it.
=> fixing URLs to EAC forms

assets/styles/component/disclaimer.scss
The top and bottom letters of the banner text "An official website of the United States government." are cutoff. This fixes that by removing `overflow: hidden`.
Fixes #100.
cc @rogeruiz @shawnbot
=> Fix cutoff banner text

layouts/404.html
This fixes a bug where the 404 page was off-center by removing ".padding-x-0" from the page grid so as to meet the new "grid-container" class in USWDS 2.0.
=> Center 404 grid

data/translations/spanish/register.toml
Change Enviélo to Envíelo in Spanish by-mail registration wording.
=> Change register Spanish wording

config/gulp/lang/spanish/state-names.json, config/gulp/translation.js, layouts/registrar/types/by-mail.html, layouts/registrar/types/in-person.html, layouts/registrar/types/not-needed.html, layouts/registrar/types/online.html, package-lock.json, package.json
With these changes the Spanish state.md files will change their external_link URL to the appropriate Spanish state page, if there is one. If no Spanish state URL is found it keeps the English state page url. 
Files changed: 
1. State-names.json:
- Added an external_link property for every state track which states needed an updated Spanish link. 
2. Translation.js:
- Created a gulp task that replaces the external link in Spanish state.md file or leaves the English external link.
=>  Replace external links for Spanish redirects

assets/styles/main.scss
This fixes an inconsistency from the old site where the "go back" footer was not visible on some screen sizes without scrolling down. 
The height of the inner state registration page's main section was shortened so that the "go back" can be seen. This reduces the amount of blank space between the page content and the footer. The main content section is also centered on the screen.
=> Inner state page sizing

data/translations/spanish/register.toml
Delete "de Guam" to end in la oficina electoral local.
=> Updated Guam's registration text

config/gulp/state-data.json
Changed mail in registration date to Sat. Oct. 24 in English and Spanish; Also changed from postmarked to received by
=> Update Mail In Date for Iowa

config/gulp/state-data.json
Running a new crazy egg report. Only want it on the home pages, California and Texas (both English and Spanish pages). I removed the crazy egg code from the other states
=> Removed Crazy Egg code from some states

config/gulp/state-data.json
New Jersey now has online registration https://voter.svrs.nj.gov/register - changed page from mail in to online registration.
=> Update NJ to from mail in to online registration

data/translations/english/register.toml
Updated "Mail-in registration deadline:" to "Register by mail deadline:" to avoid confusion with the mail-in ballot.
=> Updated Mail-in registration to Register by mail

config/gulp/state-data.json
Updated Mail in registration deadline for Main from Oct. 13 to Oct. 19
=> Updated Mail in Registration for Maine

config/gulp/state-data.json
The mail deadline for registration in Maine seems to be out of date. It would normally be 10/13 this year, but IIUC the governor pushed it back to 10/19 due to COVID (info via VoteAmerica and FiveThirtyEight):
https://www.maine.gov/governor/mills/news/governor-mills-signs-executive-order-facilitate-voting-protect-health-voters-election
=> Update Maine mail deadline to 10/19 (from 10/13)

layouts/partials/head.html, layouts/partials/language-switcher.html, layouts/partials/language-switcher1.html
Our Accessibility & Compliance Lead has advised that language subtags be removed for output on the html tag and that our language switcher should include langcodes.
=> VOTE-140 Remove langcode subtags from html output

cypress/e2e/internalLinks/internal-link-validator.cy.js
link to ticket -> https://bixal-projects.atlassian.net/browse/VOTE-790
This Pr will update the internal links test... currently it is failing in the pipeline.  After looking into it more the test was running through the whole sitemap and just timing out after running for like 15 mins.  I think that there might have been a mistake in adding the sitemap in testing a few things and this will fix that and should now run in the pipeline quicker overall. 
how to test:
- Pull down the branch 
- run `npm run start`
- spilt terminal 
- run `npm run cy:open` and check that the internal links test is passing 
- also run `npm run cy:links` to check that the headless is running and passing as well.
=> vote-790 -> fix internal links test 

cypress/e2e/tests/language-switcher.cy.js
This PR will add Portuguese to the language switcher test
to test:
1.  pull down branch 
2. run `npm run start`
3. spilt termnail 
4. run `npm run cy:test` and verify that tests are passing
=> Vote-1364 - Language Switcher Test Update

cypress/e2e/externalLinks/english-external-links-validator.cy.js, cypress/e2e/externalLinks/spanish-external-links-validator.cy.js
Fixed the locator used to identify external links in the page.
To test this, checkout this branch and run npm run cy:proofer
Guam and Virginia will fail. There is a defect to resolve this issue (https://bixal-projects.atlassian.net/jira/software/c/projects/VOTE/issues/VOTE-1448)
Verify other tests pass
=> fix failing external link tests

content/hi/register/vi.md, content/km/register/vi.md, content/ko/register/vi.md, content/tl/register/vi.md, content/vi/register/vi.md, content/ypk/register/vi.md, data/translations/hi/state-data.json, data/translations/km/state-data.json, data/translations/ko/state-data.json, data/translations/tl/state-data.json, data/translations/vi/state-data.json, data/translations/ypk/state-data.json
Removed mail deadlines from the U.S. Virgin Islands pages.
https://bixal-projects.atlassian.net/browse/VOTE-1425
=> VOTE-1425 Remove mail deadlines for U.S. Virgin Islands

config/_default/config.json, layouts/robots.txt
https://bixal-projects.atlassian.net/browse/VOTE-1439
This PR adds the robots.txt file to Hugo. For production branch (`master`) it will add the sitemap location and allow all pages. For all other branches it will exclude the sitemap link and disallow all pages.
=> VOTE-1439 add robots.txt file

content/tl/register/nj.md, data/translations/tl/state-data.json
This Pr will update the deadline property to be 'received' over 'postmarked'
link to ticket [Vote-1416](https://bixal-projects.atlassian.net/jira/software/c/projects/VOTE/boards/254?modal=detail&selectedIssue=VOTE-1416&assignee=611272e0eb7aef00694b8a97)
to test:
1. check changed files and ensure that received has been replaced over postmarked. 
2. start local and visit `http://localhost:1313/tl/register/nj/` to verify no visual regressions
=> Vote-1416 -> NJ Tagalog mail deadline property update

cypress/e2e/excludedLinks/excluded-links-english.cy.js, cypress/e2e/externalLinks/english-external-links-validator.cy.js, cypress/e2e/externalLinks/spanish-external-links-validator.cy.js, cypress/fixtures/excluded-links-english.json, cypress/fixtures/excluded-links-spanish.json
This Pr will add the Montana link that is giving a 403 error in the external link validator test.
to test 
1. pull down branch 
2. start local 
3. spilt terminal 
4. run `npm run cy:links` and verify links are passing
=> Add Montana link causing fail 

data/translations/tl/months.json
https://bixal-projects.atlassian.net/jira/software/c/projects/VOTE/boards/254?modal=detail&selectedIssue=VOTE-1442&assignee=62c492177273faf658f0d675
The month names in Tagalog were missing because the translation strings were incorrect.
=> VOTE-1442 Change month translation strings from numbers to names

content/ko/register/ar.md, data/translations/ko/state-data-2021.json, data/translations/ko/state-data.json
link to ticket: [Vote-1683](https://bixal-projects.atlassian.net/browse/VOTE-1658)
Purpose: the was a bug on the current live site for the Arkansas/Korean translation with the days our being 29 but need to be 30 
to test:
1. Pull down branch 
2. start local with `npm run start`
3. visit `http://localhost:1313/ko/register/ar/` and verify that days are now `30` and not `29`
4. can also use this link `https://cg-9e8debaf-b030-4825-a43c-cb2bc850c96c.sites.pages.cloud.gov/preview/usagov/vote-gov/bug/vote-1683-ar/ko-day-update/ko/register/ar/`
=> Vote-1683 -> Arkansas/Koren bug fix

data/translations/ht/homepage.json
ticket -> [Vote-87](https://cm-jira.usa.gov/secure/RapidBoard.jspa?rapidView=4046&projectKey=VOTE&view=detail&selectedIssue=VOTE-36&quickFilter=23166)
purpose -> ht translation was missing the search vote.gov block 
testing:
1. pull down branch 
2. run `npm run start`
3. visit `localhost:1313` and verify that search block is present on ht translation
=> vote-87 - added search block to ht translation

assets/styles/component/identifier.scss
**Testing**  
1. visit https://cg-9e8debaf-b030-4825-a43c-cb2bc850c96c.sites.pages.cloud.gov/preview/usagov/vote-gov/bug/VOTE-17-touchpoints-button-style/ in firefox.
2. Reduce the browser width to small desktop/tablet size and ensure that the centered touchpoints button is full width.
=> VOTE-17 Adjust touchpoints button style for tablet

.github/workflows/cypress-axe-workflow.yml, .github/workflows/cypress-external-links-cron-workflow.yml, .github/workflows/cypress-functional-workflow.yml, .github/workflows/cypress-links-workflow.yml, cypress/e2e/tests/footer.cy.js
This PR will update the node version to 18 since node16 has hit the end of life, and the node set up version from `v2` to `v3` 
note: the updates have to be in the default branch which is staging before we can check that the fix is working.  once this has been merged in we can check that this fix works and if not will work to ensure the correct fix is done. 
below is a screenshot of the update and a link to the changelog is [here](https://github.com/actions/setup-node/releases?page=2) look for the version 3 update
=> BUG: Update Github actions with new node set up 

.github/workflows/cypress-axe-workflow.yml, .github/workflows/cypress-external-links-cron-workflow.yml, .github/workflows/cypress-functional-workflow.yml, .github/workflows/cypress-links-workflow.yml
Ticket: [Vote-314](https://cm-jira.usa.gov/browse/VOTE-314)
This Pr will update the checkout action from version 2 to version 4 and remove the error of running node 12 from the actions run.  This will help ensure that we are using the most up to date.
link to [Change Log](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
The error we were getting:
Link to new run with no error: https://github.com/usagov/vote-gov/actions/runs/6223971737
=> VOTE-314: Updated checkout action from version 2 to 4

assets/styles/component/language-switcher.scss
Ticket: [Vote-491](https://cm-jira.usa.gov/browse/VOTE-491)
Purpose: Strings within Navajo were not getting formatted correctly in the language selector 
Testing: Visit [Preview](https://cg-9e8debaf-b030-4825-a43c-cb2bc850c96c.sites.pages.cloud.gov/preview/usagov/vote-gov/bug/vote-491-nv-bug/nv/) and verify that the language drop-down looks as expected and does not have any errors with strings
=> Vote-491: added override for menu font to match rest of site.

cypress/fixtures/site-pages.json
Ticket: [Vote-476](https://cm-jira.usa.gov/browse/VOTE-476)
Purpose:  Guam links are giving an unresponsive status at times, since the links are the current ones we need to leave them but will be skipping them for now and will add them back at a later time.
Testing:  Pull down branch and run `npm run start` spilt terminal and run `npm run cy:proofer` and check that Guam does not run. Also view changed files and ensure that Guam has been removed twice... once for English and the other for Spanish.
=> Vote-476: Remove Guam Links 

assets/scripts/state-selector.js
*Testing instructions*
1. Test entering state abbreviations in search field to make sure the state shows up (example: "dc")
2. Test entering in "ca" to get state names that have words that start with "ca" California, North Carolina, South Carolina
3. Test entering in "ma" does not show words that don't start with "ma" like Oklahoma or Alabama
=> VOTE-550 Improve state selector search

layouts/partials/deadlines.html
[Vote-351](https://cm-jira.usa.gov/browse/VOTE-351)
This PR will help resolve an accessibility error flagged on `North Dakota/Not Needed`.  The error was flagging a div that was not being used. 
Since registration was not needed for this state the text will not be rendered but the div is still present within the DOM. 
For the fix, an if statement was created that if the state was `not needed` then the div would not be rendered and for anything else, it would be 
n/a
n/a
1. visit [preview link](https://cg-9e8debaf-b030-4825-a43c-cb2bc850c96c.sites.pages.cloud.gov/preview/usagov/vote-gov/bug/vote-351-unused-container/register/nd/) and inspect and search for `class="registered-resources"`the expected result is that it will not be present 
2. navigate to another page and search for the same …
=> Vote-351: Remove Unused Container Element

data/translations/bn/footer.json, data/translations/en/footer.json, data/translations/es/footer.json, data/translations/hi/footer.json, data/translations/km/footer.json, data/translations/ko/footer.json, data/translations/nv/footer.json, data/translations/tl/footer.json, data/translations/vi/footer.json, data/translations/ypk/footer.json, data/translations/zh-hans/footer.json, data/translations/zh/footer.json, layouts/partials/contact-identifier.html
Ticket: [Vote-352](https://cm-jira.usa.gov/browse/VOTE-352)
Purpose: Removing alt text for the footer logo to match work that was done on the CMS.  This is a decorative image and text is not needed. 
Testing:
1. visit [preview link]() and inspect the logo in the footter contact and ensure that alt text is no longer present.
=> Vote-352: Remove alt text for footer logo

assets/styles/component/alert.scss, assets/styles/component/buttons.scss, assets/styles/nvrf.scss, layouts/partials/alert-notification.html, layouts/partials/header.html
[VOTE-594](https://cm-jira.usa.gov/browse/VOTE-594)
To test change config.json sitewide_alert to "true" and confirm sitewide alert styling looks correct and nvrf styling looks correct (they should be styled separately)
Button fixes on registration options page and confirm page (edit buttons) are fixed in this PR: https://github.com/usagov/vote-gov-nvrf-app/pull/111
=> VOTE-594: fix broken nvrf styling

.github/workflows/cypress-external-links-cron-workflow.yml
This Pr will update the cron run for proofer to use the node set up V4.. V3 is getting updated due to node 16 end of life.  I also updated the branch to check staging and not main to help with running more update links that get updated
=> updated branch to check staging and move to v4 for node setup

assets/scripts/state-selector.js, layouts/index.html
Ticket - [Vote-855](https://cm-jira.usa.gov/browse/VOTE-855)
Purpose - Hotfix to address issue with state selector not working when hitting link 
Testing - Visit [preview link](https://cg-9e8debaf-b030-4825-a43c-cb2bc850c96c.sites.pages.cloud.gov/preview/usagov/vote-gov/hotfix/vote-855-state-selector-mobile/) on a mobile device and check that user can hit drop down and select state from there.. and can also type in state and still to to page 
NOTE - setting to merge into main for hot fix
=> VOTE-855 HOTFIX - fix State Selector behavior on iOS

cypress/e2e/externalLinks/external-links-valdator.cy.js
Purpose: 
Updating the Maryland link that is no active to be more specific for both english and Spanish 
Testing: 
1. pull down branch and run `npm run start`
2. spilt terminal and run `npm run cy:proofer` and check that test is passing
=> Update to external links test

data/translations/es/register.json
Fix the text in the maintenance banner for Spanish
El sitio web [vote.gov](http://vote.gov/) no estará disponible entre las 6 y las 8 a.m. EST el martes 30 de julio.
=> HOTFIX: Fix the Spanish text in the maintenance banner
